@echo off
setlocal

set "REPO=D:\OneDrive - mail.scut.edu.cn\Python\MR-NLCSNN"
set "PYENV=C:\Users\user\.conda\envs\myenvPINN_test"
set "PYTHON=%PYENV%\python.exe"
set "PATH=%PYENV%;%PYENV%\Library\bin;%PYENV%\Library\usr\bin;%PYENV%\DLLs;%PYENV%\Scripts;%PATH%"
echo started %DATE% %TIME% > "%REPO%\goal_lf2pct_outputs\gain_loss_warmup_once_cmd_20260608_2006.bootstrap.log"

set "CDC_OUTPUT_ROOT=%REPO%\goal_lf2pct_outputs"
set "CDC_PROCESSED_GROUPS=D:\OneDrive - mail.scut.edu.cn\Matlab\CDCTest\Processed_Groups_new_zerophase_force_wide"
set "CDC_VAL_MODE=lf_holdout"
set "CDC_LF_VAL_RATIO=0.25"
set "CDC_LF_VAL_SEED=20260516"
set "CDC_NORM_USES_VAL=0"
set "CDC_USE_RESUME_NORM=1"
set "CDC_INCLUDE_STEP=1"
set "CDC_INCLUDE_HF=1"
set "CDC_EXTRA_DYNAMIC_NFL=1"
set "CDC_DIRECT_NFL_OUTPUT=1"
set "CDC_SLOW_GAIN_NFL=1"
set "CDC_HIDDEN=256"
set "CDC_STATE_DIM=12"
set "CDC_EPOCHS=160"
set "CDC_LR=5e-5"
set "CDC_RESUME_LR_OVERRIDE=5e-5"
set "CDC_RESUME_CHECKPOINT=%REPO%\goal_lf2pct_outputs\legacy_repro_120_epochs_20260607_201138\nlcsnn_legacy_best_all_val.pth"
set "CDC_FILE_BATCH_SIZE=32"
set "CDC_CHUNK_LEN=500"
set "CDC_WARMUP=200"
set "CDC_WARMUP_ONCE=1"
set "CDC_TRAIN_WINDOW_SECONDS=5"
set "CDC_TRAIN_WINDOW_RANDOM=0"
set "CDC_TRAIN_WINDOW_START_SECONDS=15"
set "CDC_GAIN_LOSS_WEIGHT=0.001"
set "CDC_STD_GAIN_LOSS_WEIGHT=0.002"
set "CDC_CASE_WEIGHT_REGEX=^RMS(15^|18)mm_[123](?:\\.0)?Hz$"
set "CDC_CASE_WEIGHT_REGEX_WEIGHT=3.0"
set "CDC_CASE_WEIGHT_CAP=3.0"
set "CDC_VAL_START_SECONDS=15"
set "CDC_VAL_MAX_SECONDS=5"
set "CDC_VAL_WARMUP_MS=200"
set "CDC_VAL_EVERY_SECONDS=7200"
set "CDC_MONITOR_EVERY=0"
set "CDC_VAL_ALL_EVERY=0"
set "CDC_VALIDATE_ALL_ON_EPOCH1=1"
set "CDC_PERIODIC_EVERY=10"
set "CDC_PLOT_EVERY=0"
set "CDC_TQDM=0"

cd /d "%REPO%"
echo launching python %DATE% %TIME% >> "%REPO%\goal_lf2pct_outputs\gain_loss_warmup_once_cmd_20260608_2006.bootstrap.log"
start "gain_loss_train" /B cmd /c ""%PYTHON%" "%REPO%\AA02Train\train_legacy_repro.py" > "%REPO%\goal_lf2pct_outputs\gain_loss_warmup_once_cmd_20260608_2006.out.log" 2> "%REPO%\goal_lf2pct_outputs\gain_loss_warmup_once_cmd_20260608_2006.err.log""
